export const projects = [
  {
    title: 'Portfolio',
    skills:'https://img.icons8.com/color/30/000000/html-5--v1.png', 
    skill2:"https://img.icons8.com/color/30/000000/angularjs.png",
    skill3: "https://img.icons8.com/color/30/000000/css.png",
    javascript:'https://img.icons8.com/color/30/000000/javascript--v1..png',
    typescript:"https://img.icons8.com/color/30/000000/typescript.png",
    nooode:'assets/image/iconT.png',
    mongo:'assets/image/iconT.png',
    image: 'assets/image/porfolio2.png',
    demo: '#',
    github: 'https://github.com/albertcolomer',
  },
  {
    title: 'Filter News',
    skills:'https://img.icons8.com/color/30/000000/html-5--v1.png', 
    skill2:"https://img.icons8.com/color/30/000000/angularjs.png",
    skill3: "https://img.icons8.com/color/30/000000/css.png",
    javascript:'https://img.icons8.com/color/30/000000/javascript--v1.png',
    typescript:"https://img.icons8.com/color/30/000000/typescript.png",
    nooode:'assets/image/iconT.png',
    mongo:'assets/image/iconT.png',
    image: 'assets/image/filternew.png',
    demo: '#',
    github: 'https://github.com/albertcolomer',
  },
  {
    title: 'Login Token',
    skills:'https://img.icons8.com/color/30/000000/html-5--v1.png', 
    skill2:"https://img.icons8.com/color/30/000000/angularjs.png",
    skill3: "https://img.icons8.com/color/30/000000/css.png",
    javascript:'https://img.icons8.com/color/30/000000/javascript--v1.png',
    typescript:"https://img.icons8.com/color/30/000000/typescript.png",
    nooode:'assets/image/skills/nodejs.png',
    mongo:'assets/image/skills/mongoDB.png',
    image: 'assets/image/filternew2.png',
    demo: '#',
    github: 'https://github.com/albertcolomer',
  },
  {
    title: 'Stack Mean',
    skills:'https://img.icons8.com/color/30/000000/html-5--v1.png', 
    skill2:"https://img.icons8.com/color/30/000000/angularjs.png",
    skill3: "https://img.icons8.com/color/30/000000/css.png",
    javascript:'https://img.icons8.com/color/30/000000/javascript--v1.png',
    typescript:"https://img.icons8.com/color/30/000000/typescript.png",
    nooode:'assets/image/skills/nodejs.png',
    mongo:'assets/image/skills/mongoDB.png',
    image: 'assets/image/solSalud.png',
    demo: '#',
    github: 'https://github.com/albertcolomer',
  }
];
